-- MySQL Script generated by MySQL Workbench
-- Thu May 19 00:46:26 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DEPARTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DEPARTMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTMENT` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(4) NOT NULL,
  `EMPLOYEE_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_DEPARTMENT_EMPLOYEE1_idx` (`EMPLOYEE_id` ASC),
  CONSTRAINT `fk_DEPARTMENT_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_id`)
    REFERENCES `mydb`.`EMPLOYEE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLOYEE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(8) NOT NULL,
  `sex` CHAR(2) NOT NULL,
  `work` CHAR(10) NOT NULL,
  `level` INT(11) NOT NULL,
  `id_card` CHAR(18) NOT NULL,
  `DEPARTMENT_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `id_card_UNIQUE` (`id_card` ASC),
  INDEX `fk_EMPLOYEE_DEPARTMENT1_idx` (`DEPARTMENT_id` ASC),
  CONSTRAINT `fk_EMPLOYEE_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_id`)
    REFERENCES `mydb`.`DEPARTMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATAGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CATAGORY` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CATAGORY` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `remark` TEXT(20) NULL,
  `CATAGORY_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_CATAGORY_CATAGORY1_idx` (`CATAGORY_id` ASC),
  CONSTRAINT `fk_CATAGORY_CATAGORY1`
    FOREIGN KEY (`CATAGORY_id`)
    REFERENCES `mydb`.`CATAGORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUPPLIER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SUPPLIER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SUPPLIER` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(8) NOT NULL,
  `address` VARCHAR(20) NOT NULL,
  `zipcode` CHAR(6) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `tax_number` VARCHAR(3) NOT NULL,
  `bank_account` VARCHAR(20) NOT NULL,
  `opening_bank` CHAR(8) NOT NULL,
  `contact_name` CHAR(8) NOT NULL,
  `remark` TEXT(16) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GOODS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GOODS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GOODS` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `category` CHAR(8) NOT NULL,
  `prize` DOUBLE NOT NULL,
  `amount` INT(11) NOT NULL,
  `EMPLOYEE_id` INT UNSIGNED NOT NULL,
  `CATAGORY_id` INT UNSIGNED NULL,
  `SUPPLIER_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_GOODS_EMPLOYEE1_idx` (`EMPLOYEE_id` ASC),
  INDEX `fk_GOODS_CATAGORY1_idx` (`CATAGORY_id` ASC),
  INDEX `fk_GOODS_SUPPLIER1_idx` (`SUPPLIER_id` ASC),
  CONSTRAINT `fk_GOODS_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_id`)
    REFERENCES `mydb`.`EMPLOYEE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GOODS_CATAGORY1`
    FOREIGN KEY (`CATAGORY_id`)
    REFERENCES `mydb`.`CATAGORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GOODS_SUPPLIER1`
    FOREIGN KEY (`SUPPLIER_id`)
    REFERENCES `mydb`.`SUPPLIER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEMBERSHIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MEMBERSHIP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MEMBERSHIP` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `total_cost` BIGINT(20) NOT NULL,
  `point` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONSUMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CONSUMER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CONSUMER` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(6) NOT NULL,
  `sex` CHAR(2) NOT NULL,
  `id_card` VARCHAR(20) NOT NULL,
  `MEMBERSHIP_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_CONSUMER_MEMBERSHIP1_idx` (`MEMBERSHIP_id` ASC),
  CONSTRAINT `fk_CONSUMER_MEMBERSHIP1`
    FOREIGN KEY (`MEMBERSHIP_id`)
    REFERENCES `mydb`.`MEMBERSHIP` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRANSACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TRANSACTION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TRANSACTION` (
  `number` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATETIME(8) NOT NULL,
  `total_prize` BIGINT(20) NOT NULL,
  `CONSUMER_id` INT UNSIGNED NOT NULL,
  `EMPLOYEE_id` INT UNSIGNED NOT NULL,
  `remark` TEXT(20) NULL,
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  INDEX `fk_TRANSACTION_CONSUMER1_idx` (`CONSUMER_id` ASC),
  INDEX `fk_TRANSACTION_EMPLOYEE1_idx` (`EMPLOYEE_id` ASC),
  CONSTRAINT `fk_TRANSACTION_CONSUMER1`
    FOREIGN KEY (`CONSUMER_id`)
    REFERENCES `mydb`.`CONSUMER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTION_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_id`)
    REFERENCES `mydb`.`EMPLOYEE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRANSACTION_DETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TRANSACTION_DETAIL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TRANSACTION_DETAIL` (
  `amount` INT UNSIGNED NOT NULL,
  `unit_prize` BIGINT(20) NOT NULL,
  `discount` DOUBLE NOT NULL,
  `total_prize` BIGINT(20) NOT NULL,
  `TRANSACTION_number` INT UNSIGNED NOT NULL,
  `GOODS_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`TRANSACTION_number`, `GOODS_id`),
  INDEX `fk_TRANSACTION_DETAIL_GOODS1_idx` (`GOODS_id` ASC),
  CONSTRAINT `fk_TRANSACTION_DETAIL_TRANSACTION1`
    FOREIGN KEY (`TRANSACTION_number`)
    REFERENCES `mydb`.`TRANSACTION` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTION_DETAIL_GOODS1`
    FOREIGN KEY (`GOODS_id`)
    REFERENCES `mydb`.`GOODS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
